{"name": "Authorization test with incorrect login", "status": "passed", "start": 1713953698676, "stop": 1713953698823, "uuid": "a347c80a-bb3d-4726-b5f8-45b378e6da32", "historyId": "27943f6730ab4d740c33daa26147545a", "testCaseId": "27943f6730ab4d740c33daa26147545a", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_incorrect_email_error", "labels": [{"name": "feature", "value": "Checking user authorization"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "IZY-PC"}, {"name": "thread", "value": "25448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}